const artifactsData = {
    'artifact1': {
        id: 'artifact1',
        name: 'Ancient Sword',
        image: 'assets/images/img1.jpg',
        description: 'A sword used by a freedom fighter during the war.',
        collection_no: "LWM-S-1971-001",
        accession_no: "ACC-1971-001",
        collection_date: "1971-01-01",
        contributor_name: "John Doe",
        object_type: "Weapon",
        object_head: "Sword",
        measurement: "100cm x 10cm",
        gallery_number: "Gallery 1",
        found_place: "Comilla, Bangladesh",
        experiment_formula: "N/A",
        significance_comment: "A very important artifact.",
        correction: "None"
    },
    'artifact2': {
        id: 'artifact2',
        name: 'Historic Photograph',
        image: 'assets/images/img2.jpg',
        description: 'A rare photograph capturing a pivotal moment.',
        collection_no: "LWM-P-1971-002",
        accession_no: "ACC-1971-002",
        collection_date: "1971-02-02",
        contributor_name: "Jane Smith",
        object_type: "Photograph",
        object_head: "Photograph",
        measurement: "20cm x 30cm",
        gallery_number: "Gallery 1",
        found_place: "Dhaka, Bangladesh",
        experiment_formula: "N/A",
        significance_comment: "A very important photograph.",
        correction: "None"
    },
    'artifact3': {
        id: 'artifact3',
        name: 'Personal Diary',
        image: 'assets/images/img3.jpg',
        description: 'The personal diary of a war hero, detailing daily life.',
        collection_no: "LWM-D-1971-003",
        accession_no: "ACC-1971-003",
        collection_date: "1971-03-03",
        contributor_name: "Abdul Karim",
        object_type: "Document",
        object_head: "Diary",
        measurement: "15cm x 10cm",
        gallery_number: "Gallery 2",
        found_place: "Sylhet, Bangladesh",
        experiment_formula: "N/A",
        significance_comment: "A very important diary.",
        correction: "None"
    },
    'artifact4': {
        id: 'artifact4',
        name: 'Freedom Fighter\'s Uniform',
        image: 'assets/images/img4.jpg',
        description: 'A uniform worn by a freedom fighter.',
        collection_no: "LWM-U-1971-004",
        accession_no: "ACC-1971-004",
        collection_date: "1971-04-04",
        contributor_name: "Anonymous",
        object_type: "Uniform",
        object_head: "Uniform",
        measurement: "N/A",
        gallery_number: "Gallery 2",
        found_place: "Chittagong, Bangladesh",
        experiment_formula: "N/A",
        significance_comment: "A very important uniform.",
        correction: "None"
    },
    'artifact5': {
        id: 'artifact5',
        name: 'Surrender Instrument',
        image: 'assets/images/img5.jpg',
        description: 'The instrument of surrender signed after the war.',
        collection_no: "LWM-I-1971-005",
        accession_no: "ACC-1971-005",
        collection_date: "1971-12-16",
        contributor_name: "Government of Bangladesh",
        object_type: "Instrument",
        object_head: "Instrument",
        measurement: "50cm x 70cm",
        gallery_number: "Gallery 3",
        found_place: "Dhaka, Bangladesh",
        experiment_formula: "N/A",
        significance_comment: "The official instrument of surrender.",
        correction: "None"
    }
};